### ISSUE TITLE
Submit endpoint 500 error

### ISSUE THREAD

**Issue by blankdots** [CSCfi/metadata-submitter#65]
#### Describe the bug

`submit` endpoint seems to have trouble parsing a submission
this is produced in the logs
```
[2020-06-26 11:27:09][server][14286 MainProcess][INFO    ](L:45) init: Server configurations and routes loaded
======== Running on http://0.0.0.0:5430 ========
(Press CTRL+C to quit)
[2020-06-26 11:29:35][server][14286 MainProcess][INFO    ](L:60) create_metadata_object: Inserting file to database succeeded: study, text/xml
[2020-06-26 11:29:42][server][14286 MainProcess][INFO    ](L:55) _json_exception: b'{"type": "about:blank", "title": "Not Found", "detail": "Not Found", "instance": "/objects/study/EDAG2558991194919604"}'
[2020-06-26 11:30:07][server][14286 MainProcess][INFO    ](L:55) _json_exception: b'{"type": "about:blank", "title": "Bad Request", "detail": "There must be a submission.xml file in submission.", "instance": "/submit"}'
[2020-06-26 11:31:02][server][14286 MainProcess][INFO    ](L:55) _json_exception: b'{"type": "about:blank", "title": "Bad Request", "detail": "Not ok type", "instance": "/submit"}'
[2020-06-26 11:31:15][aiohttp.server][14286 MainProcess][ERROR   ](L:307) log_exception: Error handling request
Traceback (most recent call last):
  File "/home/stenegru/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/stenegru/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/stenegru/.pyenv/versions/3.7.7/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/stenegru/.pyenv/versions/3.7.7/lib/python3.7/site-packages/metadata_backend/api/middlewares.py", line 27, in http_error_handler
    response = await handler(req)
  File "/home/stenegru/.pyenv/versions/3.7.7/lib/python3.7/site-packages/metadata_backend/api/handlers.py", line 126, in submit
    actions[attr["schema"]] = action
KeyError: 'schema'
```

#### To Reproduce
Steps to reproduce the behaviour:

0. using `feature/add-better-xml-parsing` branch but error should be replicable on other branches as well
1. Start a server and do a curl with
```
curl --location --request POST 'localhost:5430/submit' \
--header 'Accept: */*' \
--form 'submission=<?xml version = '\''1.0'\'' encoding = '\''UTF-8'\''?>
<SUBMISSION_SET>
    <SUBMISSION alias="Thu_Oct_08_14_06_52_BST_2015_EBI" center_name="EBI"
                submission_date="2015-10-08T14:07:03.337+01:00" accession="ERA521986"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <IDENTIFIERS>
            <PRIMARY_ID>ERA521986</PRIMARY_ID>
            <SUBMITTER_ID namespace="EBI">Thu_Oct_08_14_06_52_BST_2015_EBI</SUBMITTER_ID>
        </IDENTIFIERS>
        <ACTIONS>
            <ACTION>
                <ADD schema="study" source="SRP000539.xml"/>
            </ACTION>
            <ACTION>
                <ADD schema="sample" source="SRS001433.xml"/>
            </ACTION>
        </ACTIONS>
    </SUBMISSION>
</SUBMISSION_SET>
'
```
or in python

```
import requests

url = "localhost:5430/submit"

payload = {'submission': '<?xml version = \'1.0\' encoding = \'UTF-8\'?>
<SUBMISSION_SET>
    <SUBMISSION alias="Thu_Oct_08_14_06_52_BST_2015_EBI" center_name="EBI"
                submission_date="2015-10-08T14:07:03.337+01:00" accession="ERA521986"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <IDENTIFIERS>
            <PRIMARY_ID>ERA521986</PRIMARY_ID>
            <SUBMITTER_ID namespace="EBI">Thu_Oct_08_14_06_52_BST_2015_EBI</SUBMITTER_ID>
        </IDENTIFIERS>
        <ACTIONS>
            <ACTION>
                <ADD schema="study" source="SRP000539.xml"/>
            </ACTION>
            <ACTION>
                <ADD schema="sample" source="SRS001433.xml"/>
            </ACTION>
        </ACTIONS>
    </SUBMISSION>
</SUBMISSION_SET>
'}
files = [

]
headers = {
  'Accept': '*/*'
}

response = requests.request("POST", url, headers=headers, data = payload, files = files)

print(response.text.encode('utf8'))
```
2. get a `500` error

#### Expected behavior

instead of `500` error get a response of `200` and response body `[]`

#### Additional context

Trouble line is line `126 ` from handlers .py it should be `actions[attr["attributes"]["schema"]] = action`

**Comment by blankdots** [comment]
cannot replicate on latest `develop` branch so closing.
