### ISSUE TITLE
Fix server crash on sending non-valid schema to /validate endpoint

### ISSUE THREAD

**Issue by otahontas** [CSCfi/metadata-submitter#83]
#### Describe the bug

Sending file with non-valid schema name to /validate-endpoint crashes server and returns 500.

#### To Reproduce
Steps to reproduce the behaviour:
1. Send form to validate-endpoint with non-valid schema name.
2. Server crashes

#### Expected behavior
Expected server to respond with clear message about wrong schema name.

#### Stacktrace
 While testing submission in frontend, I managed to send request to /validate with schema type `null` and file being `null`. This resulted following stacktrace:

```
metadata_submitter_backend_dev | [2020-07-10 13:01:37][server][1 MainProcess][INFO    ](L:40) init: Server configurations and routes loaded
metadata_submitter_database_dev | 2020-07-10T13:01:38.000+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
metadata_submitter_backend_dev | [2020-07-10 13:01:55][aiohttp.server][1 MainProcess][ERROR   ](L:355) log_exception: Error handling request
metadata_submitter_backend_dev | Traceback (most recent call last):
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 1506, in open_local_file
metadata_submitter_backend_dev |     stats = os.stat(localfile)
metadata_submitter_backend_dev | FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/null'
metadata_submitter_backend_dev | 
metadata_submitter_backend_dev | During handling of the above exception, another exception occurred:
metadata_submitter_backend_dev | 
metadata_submitter_backend_dev | Traceback (most recent call last):
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
metadata_submitter_backend_dev |     resp = await task
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
metadata_submitter_backend_dev |     resp = await handler(request)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
metadata_submitter_backend_dev |     return await handler(request)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/metadata_backend/api/middlewares.py", line 29, in http_error_handler
metadata_submitter_backend_dev |     response = await handler(req)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/metadata_backend/api/handlers.py", line 183, in validate
metadata_submitter_backend_dev |     schema.validate(xml_content)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 1305, in validate
metadata_submitter_backend_dev |     for error in self.iter_errors(source, path, schema_path, use_defaults, namespaces):
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/xmlschema/validators/schema.py", line 1334, in iter_errors
metadata_submitter_backend_dev |     source = XMLResource(source, defuse=self.defuse, timeout=self.timeout, lazy=False)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/xmlschema/resources.py", line 342, in __init__
metadata_submitter_backend_dev |     self.source = source
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/xmlschema/resources.py", line 359, in __setattr__
metadata_submitter_backend_dev |     self._root, self._text, self._url = self._fromsource(value)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/site-packages/xmlschema/resources.py", line 418, in _fromsource
metadata_submitter_backend_dev |     with urlopen(url, timeout=self.timeout) as resource:
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
metadata_submitter_backend_dev |     return opener.open(url, data, timeout)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
metadata_submitter_backend_dev |     response = self._open(req, data)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
metadata_submitter_backend_dev |     '_open', req)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
metadata_submitter_backend_dev |     result = func(*args)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 1484, in file_open
metadata_submitter_backend_dev |     return self.open_local_file(req)
metadata_submitter_backend_dev |   File "/usr/local/lib/python3.7/urllib/request.py", line 1523, in open_local_file
metadata_submitter_backend_dev |     raise URLError(exp)
metadata_submitter_backend_dev | urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '/usr/src/app/null'>
```

#### Additional context

Clearly backend doesn't check if schema type exists, so check for this can be added first (see other methods in handlers for example). However, this sort of error where schma doesn't exist should be catched and SchemaNotFoundExpection should be raised. That raising needs to be debugged as well.

**Comment by blankdots** [comment]
@otahontas I cannot replicate on branch develop :thinking: with Postman.

some js code of my request:
```
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'localhost:5430/validate',
  'headers': {
    'Accept': '*/*'
  },
  formData: {
    'null': 'null'
  }
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});

```
maybe doing something wrong ?

**Comment by blankdots** [comment]
ok ...this is what replicates it:
```
var request = require('request');
var fs = require('fs');
var options = {
  'method': 'POST',
  'url': 'localhost:5430/validate',
  'headers': {
    'Accept': '*/*'
  },
  formData: {
    'study': {
      'value': fs.createReadStream('/path/to/file'),
      'options': {
        'filename': 'filename'
        'contentType': null
      }
    }
  }
};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```
